antora:
  extensions:
  - require: ./antora-navigator-extension
    config_file: ./antora-navigator.yml

site:
  title: Kerem Bozdas
  url: https://kerembozdas.com/wiki
  start_page: wiki::index.adoc

content:
  sources:
  - url: https://github.com/krmbzds/wiki.git
  - url: https://github.com/krmbzds/snippets.git
  - url: https://github.com/krmbzds/lists.git

asciidoc:
  attributes:
    experimental: ''
    hide-uri-scheme: '@'
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    table-frame: 'none@'
    table-grid: 'rows@'
    toc: ~
    xrefstyle: short

ui:
  bundle:
    url: https://gitlab.com/krmbzds/antora-ui-custom/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./public
  clean: true

runtime:
  fetch: true
